### ISSUE TITLE
Is there an example of this being used in VBA?

### ISSUE THREAD

**Issue by bsacheri** [dzzie/scivb2#2]
I'm wondering how difficult it would be to implement and deploy this as an ActiveX control in an **MS Access** form?  I'd like to built a developer add-in utility (mainly for myself) that will give me a text editing control that includes SQL highlighting.  I don't need much more than copying text in, letting the user manipulate it, and copying it back out.  Does anyone have an interest in making a sample **.accdb** file using **scivb2**?

The example below shows the interface I have so far.  It allows me to convert an Access Jet query into T-SQL.   I'm currently using the Access TextBox with RichText mode turned on.  I'm highlighting the SQL myself via code parsing but it has some quirks.  I'd like to let Scintilla do the work.

![image](https://user-images.githubusercontent.com/25061292/73149693-7f187900-4090-11ea-8df5-d1fd3367f323.png)

**Comment by dzzie** [comment]
I havent been receiving notifications of issues for some reason. The ocx control in this repo should be able to be embedded in an access form without a problem in the normal way. The SQL syntax parser has been compiled into Scintinilla. I am afraid I do not have an access install to create a demo for it. 

You can find a sql.bin highlighter file in \others\ORIGINAL_SCIVB.zip\highlighters folder. I have not tested it though.

**Comment by bsacheri** [comment]
Thanks for getting back to me.  From a command prompt I ran `regsvr32 scivb2.ocx` to register this ActiveX control.  Then from within Access I was able to insert the control from the Active X menu option on the ribbon:

![image](https://user-images.githubusercontent.com/25061292/89364257-1d207800-d6a0-11ea-8be6-ea04c02a377f.png)

After I open the form, I can paste SQL into it.  Wow!  That was easy.

![image](https://user-images.githubusercontent.com/25061292/89363969-73d98200-d69f-11ea-928a-66f247d69f2e.png)

As you can see, some of the text is formatted.  How can I specify that I want to use SQL highlighting instead of some other language?  Is there another OCX or interface I can use to configure additional properties not exposed on this control?

**Comment by dzzie** [comment]
The .loadhighlighter method passing it the path of the sql.bin file I mentioned and make sure the set active argument is true probably default. It is a big complicated control but it can do a lot

**Comment by dzzie** [comment]
this might be of interest. I started playing around trying to create an auto complete editor for SQL query generation. I seem to have had to tweak the sql.hilighter file a bit too the syntax highlight wasnt working off the bat for some reason but seems to be reliable now (fingers crossed)

https://www.vbforums.com/showthread.php?889424-sql-autocomplete-control
